version: "3.9"
services:
  db:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_DB: "monitoring-service-app"
      POSTGRES_USER: "dayadanya"
      POSTGRES_PASSWORD: "dayadanya"
    ports:
      - "5432:5432"